import { 
  EventCategory, 
  DecorationStyleItem, 
  PackageItem, 
  ServiceItem, 
  PortfolioProject, 
  BeforeAfterItem, 
  TestimonialItem,
  SiteSettings 
} from '../types';

export const EVENT_CATEGORIES: {
  id: EventCategory;
  name: EventCategory;
  description: string;
  tagline: string;
  badge: string;
  gradient: string;
}[] = [
  {
    id: 'Wedding',
    name: 'Wedding',
    tagline: 'Grand Mandapams & Royal Stages',
    description: 'Bespoke stage setups, magnificent floral mandapams, elegant entryway tunnels, and regal couple seating.',
    badge: 'Flagship Decor',
    gradient: 'from-[#3A2618] to-[#1C140E]',
  },
  {
    id: 'Engagement',
    name: 'Engagement',
    tagline: 'Romantic Backdrops & Floral Arches',
    description: 'Enchanting floral installations, delicate fairy lights, personalized monogram backdrops, and ring ceremony stages.',
    badge: 'Trending',
    gradient: 'from-[#382025] to-[#1A0E11]',
  },
  {
    id: 'Birthday',
    name: 'Birthday',
    tagline: 'Themed Celebrations & Grand Balloon Art',
    description: 'Immersive themed backdrops, custom name cutouts, balloon arches, kids fantasy sets, and milestone adult parties.',
    badge: 'Popular',
    gradient: 'from-[#2B2338] to-[#140F1D]',
  },
  {
    id: 'Baby Shower',
    name: 'Baby Shower',
    tagline: 'Pastel Dreams & Warm Welcomes',
    description: 'Dreamy pastel tones, cloud backdrops, floral cradles, Seemantham traditional arrangements, and photo booth frames.',
    badge: 'Emotional',
    gradient: 'from-[#382D24] to-[#1D1610]',
  },
  {
    id: 'Haldi',
    name: 'Haldi',
    tagline: 'Vibrant Yellows & Marigold Splendor',
    description: 'Bright marigold canopies, traditional brass urli setups, colorful drapes, floral umbrellas, and playful photo points.',
    badge: 'Festive',
    gradient: 'from-[#3D3012] to-[#1E1705]',
  },
  {
    id: 'Mehendi',
    name: 'Mehendi',
    tagline: 'Boho Drapes, Cushions & Greenery',
    description: 'Kaleidoscope colors, low-seating bohemian lounges, hanging tassel hangings, swings (jhoola), and floral crowns.',
    badge: 'Vibrant',
    gradient: 'from-[#1E3326] to-[#0A1A11]',
  },
  {
    id: 'Anniversary',
    name: 'Anniversary',
    tagline: 'Romantic Candlelight & Timeless Charm',
    description: 'Intimate candlelit dinners, milestone silver & gold jubilee setups, memory photo walls, and lavish stage decor.',
    badge: 'Milestone',
    gradient: 'from-[#33222B] to-[#190F14]',
  },
  {
    id: 'Traditional Celebrations',
    name: 'Traditional Celebrations',
    tagline: 'Pooja, Housewarming & Upanayanam',
    description: 'Authentic temple architecture backdrops, banana leaf styling, fresh jasmine and marigold garlands, brass lamps, and floral rangolis.',
    badge: 'Authentic',
    gradient: 'from-[#382718] to-[#1D1208]',
  },
  {
    id: 'Corporate Events',
    name: 'Corporate Events',
    tagline: 'Sleek Stage Backdrops & Gala Decor',
    description: 'Modern stage designs, corporate branding backdrops, award gala centerpieces, audio-visual integration, and entryway arches.',
    badge: 'Professional',
    gradient: 'from-[#1F2937] to-[#111827]',
  },
  {
    id: 'Home Events',
    name: 'Home Events',
    tagline: 'Intimate & Cozy Living Space Transformations',
    description: 'Compact yet breathtaking setups customized specifically for living rooms, balconies, terraces, and backyard gardens.',
    badge: 'Cozy & Chic',
    gradient: 'from-[#2B2825] to-[#141210]',
  },
  {
    id: 'Customized Celebrations',
    name: 'Customized Celebrations',
    tagline: 'Your Unique Vision Crafted Into Reality',
    description: 'Completely customized concept decor designed from your Pinterest boards and bespoke vision.',
    badge: 'Bespoke',
    gradient: 'from-[#29202D] to-[#120D14]',
  },
];

export const DECORATION_STYLES: DecorationStyleItem[] = [
  {
    id: 'style-1',
    name: 'Royal',
    slug: 'royal',
    description: 'Opulent velvet drapes, gold carved pillars, crystal chandeliers, and grand palace-inspired decor aesthetics.',
    cover_image: '',
    tags: ['Gold Accents', 'Velvet', 'Chandeliers', 'Regal Mandap'],
    sort_order: 1,
  },
  {
    id: 'style-2',
    name: 'Floral',
    slug: 'floral',
    description: 'Abundance of fresh exotic carnations, roses, orchids, and cascading floral chandeliers and arches.',
    cover_image: '',
    tags: ['Fresh Flowers', 'Cascading Florals', 'Fragrant Blooms'],
    sort_order: 2,
  },
  {
    id: 'style-3',
    name: 'Minimal',
    slug: 'minimal',
    description: 'Understated elegance, clean lines, warm ambient lighting, geometric framing, and subtle earthy accents.',
    cover_image: '',
    tags: ['Clean Lines', 'Modernist', 'Subtle Glow', 'Aesthetic'],
    sort_order: 3,
  },
  {
    id: 'style-4',
    name: 'Traditional',
    slug: 'traditional',
    description: 'Rooted in Indian heritage with brass urlis, temple pillars, fresh marigold torans, and auspicious bell motifs.',
    cover_image: '',
    tags: ['Marigold', 'Brass Elements', 'Pooja Decor', 'Heritage'],
    sort_order: 4,
  },
  {
    id: 'style-5',
    name: 'Luxury',
    slug: 'luxury',
    description: 'High-end mirrored stages, acrylic crystal structures, premium LED washes, and couture floral arrangements.',
    cover_image: '',
    tags: ['Mirrored Stage', 'High-End Florals', 'Architectural'],
    sort_order: 5,
  },
  {
    id: 'style-6',
    name: 'Modern',
    slug: 'modern',
    description: 'Contemporary neon signage, acrylic panels, asymmetric arches, and fashionable chic silhouettes.',
    cover_image: '',
    tags: ['Neon Art', 'Asymmetry', 'Chic Accents', 'Trendy'],
    sort_order: 6,
  },
  {
    id: 'style-7',
    name: 'Pastel',
    slug: 'pastel',
    description: 'Soft blush pinks, mint sage, lavender, baby blue, and gentle golden highlights creating an ethereal mood.',
    cover_image: '',
    tags: ['Blush Pink', 'Sage Green', 'Ethereal', 'Baby Shower'],
    sort_order: 7,
  },
  {
    id: 'style-8',
    name: 'Rustic',
    slug: 'rustic',
    description: 'Raw wooden logs, macramé weaves, jute rugs, fairy lights, pampas grass, and warm boho textures.',
    cover_image: '',
    tags: ['Pampas Grass', 'Boho Lounge', 'Wooden Frames', 'Earthy'],
    sort_order: 8,
  },
  {
    id: 'style-9',
    name: 'Colorful',
    slug: 'colorful',
    description: 'Vibrant marigolds, rainbow pom-poms, multi-colored dupattas, and cheerful festive celebration styling.',
    cover_image: '',
    tags: ['Festive', 'Haldi Mehendi', 'Rainbow Drapes'],
    sort_order: 9,
  },
];

export const INITIAL_SERVICES: ServiceItem[] = [
  {
    id: 'srv-1',
    title: 'Wedding Stage & Mandapam Decor',
    slug: 'wedding-mandapam-decor',
    short_desc: 'Bespoke wedding stages, temple mandapams, and regal couple backdrops customized to your rituals and venue.',
    full_desc: 'From traditional South Indian temple mandapams with banana trunks and brass urlis to modern luxury flower wall stages with crystal chandeliers, we handle complete concept design and venue styling in Hyderabad.',
    category: 'Weddings',
    icon_name: 'Crown',
    is_featured: true,
    sort_order: 1,
  },
  {
    id: 'srv-2',
    title: 'Haldi & Mehendi Thematic Setups',
    slug: 'haldi-mehendi-setups',
    short_desc: 'Vibrant marigold canopies, brass urli bathing setups, floral jhoolas, and bohemian photo lounges.',
    full_desc: 'Bring energetic, colorful joy to your pre-wedding festivities. We create photogenic Haldi spots with customized yellow floral curtains, wooden props, and colorful Mehendi seating.',
    category: 'Pre-Wedding',
    icon_name: 'Sun',
    is_featured: true,
    sort_order: 2,
  },
  {
    id: 'srv-3',
    title: 'Birthday & Milestone Celebrations',
    slug: 'birthday-milestone-decor',
    short_desc: 'Immersive themes, 3D character backdrops, luxury organic balloon garlands, and dessert table styling.',
    full_desc: 'Whether it is a 1st birthday wonderland, sweet sixteen, or a milestone 50th golden jubilee, our design team produces eye-catching themed installations.',
    category: 'Birthdays',
    icon_name: 'PartyPopper',
    is_featured: true,
    sort_order: 3,
  },
  {
    id: 'srv-4',
    title: 'Engagement & Ring Ceremony Styling',
    slug: 'engagement-styling',
    short_desc: 'Romantic floral rings, neon monograms, ambient candle pathways, and sophisticated couple seating.',
    full_desc: 'Celebrate your special promise with an intimate or grand engagement setup tailored with exquisite roses, fairy-light canopies, and custom monogram logos.',
    category: 'Engagements',
    icon_name: 'Heart',
    is_featured: true,
    sort_order: 4,
  },
  {
    id: 'srv-5',
    title: 'Baby Shower & Naming Ceremony',
    slug: 'baby-shower-cradle-decor',
    short_desc: 'Floral cradle decoration, Seemantham traditional backdrops, and soothing pastel theme arrangements.',
    full_desc: 'Welcome the new blessing with blessed floral cradles, traditional greenery, or contemporary pastel clouds and teddy bear setups.',
    category: 'Baby Showers',
    icon_name: 'Smile',
    is_featured: true,
    sort_order: 5,
  },
  {
    id: 'srv-6',
    title: 'Corporate Galas & Annual Meets',
    slug: 'corporate-event-decor',
    short_desc: 'Executive stage designs, branded photo backdrops, lighting truss, and elegant table centerpieces.',
    full_desc: 'Sophisticated event decor for corporate conferences, awards nights, product launches, and gala dinners in Hyderabad IT corridors.',
    category: 'Corporate',
    icon_name: 'Building',
    is_featured: true,
    sort_order: 6,
  },
];

export const INITIAL_PACKAGES: PackageItem[] = [
  {
    id: 'pkg-1',
    name: 'Essential Celebration',
    tier: 'Essential',
    tag_line: 'Ideal for intimate home celebrations & small gatherings',
    starting_price: 'Starting from ₹20,000',
    description: 'A curated, clean decoration package designed for apartments, small banquets, and intimate home ceremonies.',
    inclusions: [
      'Backdrop setup (up to 10ft x 8ft)',
      'Artificial/Fresh floral accents combination',
      'Warm LED spotlight illumination',
      'Name cutout / event sign board',
      'Welcome easel stand at entrance',
      'Setup & teardown included',
    ],
    is_popular: false,
    sort_order: 1,
  },
  {
    id: 'pkg-2',
    name: 'Signature Grandeur',
    tier: 'Signature',
    tag_line: 'Our most popular choice for engagements, Haldi & large birthdays',
    starting_price: 'Starting from ₹45,000',
    description: 'Elevated aesthetics with rich floral styling, custom stage elements, and themed guest photo booth.',
    inclusions: [
      'Custom stage backdrop (up to 16ft x 10ft)',
      'Rich fresh floral arrangements & drapes',
      'Dedicated themed photo booth area',
      'Grand entryway floral arch / walkway',
      'Couple seating / Jhoola setup with styling',
      'Dynamic warm & ambient mood lighting',
      'On-site decor coordinator during setup',
    ],
    is_popular: true,
    sort_order: 2,
  },
  {
    id: 'pkg-3',
    name: 'Royal Bespoke Studio',
    tier: 'Royal Bespoke',
    tag_line: 'Complete luxury venue transformation for weddings & grand receptions',
    starting_price: 'Starting from ₹95,000',
    description: 'An all-inclusive couture event experience crafted from 3D design concept to breathtaking reality.',
    inclusions: [
      'Grand stage / Mandapam with custom pillars & ceiling drapes',
      'Exotic fresh florals (carnations, orchids, roses, lilies)',
      'Royal entryway tunnel with chandeliers & fairy lights',
      'VIP guest table centerpieces & dining area decor',
      'Personalized couple monogram & neon installations',
      'Complete ambient lighting, haze & warm par cans',
      'Dedicated lead decorator & support crew',
    ],
    is_popular: false,
    sort_order: 3,
  },
];

export const INITIAL_PORTFOLIO: PortfolioProject[] = [
  {
    id: 'port-1',
    title: 'The Royal Nizam Engagement at Banjara Hills',
    slug: 'royal-nizam-engagement-banjara-hills',
    event_type: 'Engagement',
    location: 'Banjara Hills, Hyderabad',
    theme: 'Royal Mughal • Gold & White Florals • Velvet',
    description: 'A regal evening engagement featuring a 24-foot grand floral wall, cascading crystal chandeliers, and vintage gold mirror panels tailored for a royal couple.',
    client_requirement: 'A royal, heritage-inspired engagement setup with rich white orchids and champagne gold accents that looks breathtaking in photos.',
    cover_image: '',
    tags: ['Royal', 'Banjara Hills', 'Orchids', 'Chandeliers', 'Gold'],
    is_featured: true,
    is_published: true,
    sort_order: 1,
    created_at: '2026-09-15T10:00:00Z',
    updated_at: '2026-09-15T10:00:00Z',
    images: [
      {
        id: 'img-1-1',
        portfolio_id: 'port-1',
        image_url: '',
        caption: 'Grand Stage & Couple Seating',
        category_section: 'Stage',
        is_cover: true,
        sort_order: 1,
      },
      {
        id: 'img-1-2',
        portfolio_id: 'port-1',
        image_url: '',
        caption: 'Tunnel Entryway with Fairy Canopies',
        category_section: 'Entrance',
        is_cover: false,
        sort_order: 2,
      },
      {
        id: 'img-1-3',
        portfolio_id: 'port-1',
        image_url: '',
        caption: 'Personalized Monogram Photo Booth',
        category_section: 'Photo Booth',
        is_cover: false,
        sort_order: 3,
      },
    ],
  },
  {
    id: 'port-2',
    title: 'Sunlit Marigold & Brass Haldi at Jubilee Hills',
    slug: 'sunlit-marigold-haldi-jubilee-hills',
    event_type: 'Haldi',
    location: 'Jubilee Hills, Hyderabad',
    theme: 'Traditional Sunshine • Marigold • Brass Urli',
    description: 'Vibrant outdoor lawn Haldi ceremony transformed with 500+ kilos of fresh yellow & orange marigolds, a heritage brass urli for the groom and bride, and decorative floral canopies.',
    client_requirement: 'An authentic South Indian Haldi aesthetic filled with bright yellow tones, natural sunlight, and traditional flower curtains.',
    cover_image: '',
    tags: ['Haldi', 'Marigold', 'Jubilee Hills', 'Brass Urli', 'Traditional'],
    is_featured: true,
    is_published: true,
    sort_order: 2,
    created_at: '2026-09-10T10:00:00Z',
    updated_at: '2026-09-10T10:00:00Z',
    images: [
      {
        id: 'img-2-1',
        portfolio_id: 'port-2',
        image_url: '',
        caption: 'Main Brass Urli Haldi Mandap',
        category_section: 'Stage',
        is_cover: true,
        sort_order: 1,
      },
    ],
  },
  {
    id: 'port-3',
    title: 'Ethereal Botanical Wedding at Gachibowli',
    slug: 'ethereal-botanical-wedding-gachibowli',
    event_type: 'Wedding',
    location: 'Gachibowli, Hyderabad',
    theme: 'Pastel Garden • Rose Gold • Temple Pillars',
    description: 'A grand indoor banquet wedding featuring a hand-carved mandap wrapped in thousands of blush pink roses, gypsophila, and illuminated water-fountain aisles.',
    client_requirement: 'A fairy-tale romantic mandapam that blends classic South Indian sacred architecture with dreamy contemporary pastel floral arches.',
    cover_image: '',
    tags: ['Wedding', 'Mandapam', 'Gachibowli', 'Pastel Florals', 'Luxury'],
    is_featured: true,
    is_published: true,
    sort_order: 3,
    created_at: '2026-08-28T10:00:00Z',
    updated_at: '2026-08-28T10:00:00Z',
    images: [
      {
        id: 'img-3-1',
        portfolio_id: 'port-3',
        image_url: '',
        caption: 'Blush Pink Sacred Mandapam',
        category_section: 'Mandapam',
        is_cover: true,
        sort_order: 1,
      },
    ],
  },
  {
    id: 'port-4',
    title: 'Bohemian Twilight 1st Birthday at Madhapur',
    slug: 'bohemian-twilight-birthday-madhapur',
    event_type: 'Birthday',
    location: 'Madhapur, Hyderabad',
    theme: 'Safari Chic • Organic Balloons • Wooden Arches',
    description: 'Custom baby celebration featuring a 3D hot air balloon centerpiece, sage green and champagne organic balloon clusters, and personalized LED name light.',
    client_requirement: 'A non-commercial, aesthetically pleasing 1st birthday theme that looks chic and elegant for family portraits.',
    cover_image: '',
    tags: ['Birthday', 'Balloons', 'Madhapur', 'Pastel', '1st Birthday'],
    is_featured: true,
    is_published: true,
    sort_order: 4,
    created_at: '2026-08-14T10:00:00Z',
    updated_at: '2026-08-14T10:00:00Z',
    images: [
      {
        id: 'img-4-1',
        portfolio_id: 'port-4',
        image_url: '',
        caption: 'Safari Cloud Balloon Backdrop',
        category_section: 'Stage',
        is_cover: true,
        sort_order: 1,
      },
    ],
  },
];

export const INITIAL_BEFORE_AFTER: BeforeAfterItem[] = [
  {
    id: 'ba-1',
    title: 'Empty Convention Hall to Grand Nizam Wedding Stage',
    event_type: 'Wedding',
    venue_location: 'Gachibowli Convention Center, Hyderabad',
    description: 'How SMS Events and Decors transformed a bare concrete stage into a 30-foot luxury floral palace within 8 hours.',
    before_image: '',
    after_image: '',
    is_published: true,
    sort_order: 1,
    created_at: '2026-09-01T10:00:00Z',
  },
  {
    id: 'ba-2',
    title: 'Bare Terrace Lawn to Dreamy Fairy Light Haldi Canopy',
    event_type: 'Haldi',
    venue_location: 'Private Villa Terrace, Jubilee Hills',
    description: 'Transformation of a simple open terrace into an intimate yellow marigold haven with brass urli and swing decor.',
    before_image: '',
    after_image: '',
    is_published: true,
    sort_order: 2,
    created_at: '2026-08-20T10:00:00Z',
  },
];

export const INITIAL_TESTIMONIALS: TestimonialItem[] = [
  {
    id: 'test-1',
    customer_name: 'Ananya & Karthik Reddy',
    event_type: 'Wedding',
    event_date: 'August 2026',
    location: 'Banjara Hills, Hyderabad',
    rating: 5,
    review_text: 'SMS Events and Decors made our wedding reception look straight out of a royal fairy tale. The floral mandap and entryway tunnel received endless compliments from all 600 guests. The team was punctual, respectful, and delivered beyond our expectations!',
    is_featured: true,
    is_published: true,
    sort_order: 1,
    created_at: '2026-08-25T10:00:00Z',
  },
  {
    id: 'test-2',
    customer_name: 'Suresh & Preeti Varma',
    event_type: 'Haldi',
    event_date: 'September 2026',
    location: 'Jubilee Hills, Hyderabad',
    rating: 5,
    review_text: 'The Haldi setup was so lively and vibrant! The brass urli, fresh marigold chandeliers, and photo booth frames made our pictures look stunning. They handled everything with absolute zero stress for our family.',
    is_featured: true,
    is_published: true,
    sort_order: 2,
    created_at: '2026-09-12T10:00:00Z',
  },
  {
    id: 'test-3',
    customer_name: 'Deepika & Vikram Rao',
    event_type: 'Birthday',
    event_date: 'September 2026',
    location: 'Madhapur, Hyderabad',
    rating: 5,
    review_text: 'We booked SMS Events for our daughter’s 1st birthday. The customized safari pastel setup and balloon art was top notch. Transparent pricing with no hidden charges at all!',
    is_featured: true,
    is_published: true,
    sort_order: 3,
    created_at: '2026-09-18T10:00:00Z',
  },
];

export const INITIAL_SITE_SETTINGS: SiteSettings = {
  site_name: 'SMS Events and Decors',
  hero_heading: 'We Turn Celebrations Into Experiences.',
  hero_subheading: 'Bespoke decorations for weddings, engagements, birthdays, and unforgettable moments.',
  service_area: 'Hyderabad, Telangana & Andhra Pradesh',
  contact_phone: '+91 79956 44101 / +91 99123 88101',
  contact_whatsapp: '+917995644101',
  contact_email: 'smsevents@gmail.com',
  address: 'Plot No: 141, Vishwakarma Colony, Suraram, Hyderabad, Telangana 500055',
  instagram_url: 'https://instagram.com/smseventsanddecors',
  facebook_url: 'https://facebook.com/smseventsanddecors',
  youtube_url: 'https://youtube.com/@smseventsanddecors',
  experience_years: '8+',
  events_completed: '450+',
  happy_clients: '500+',
};
